
apiVersion: apps/v1
kind: Deployment
metadata:
  # This name must match the K8S_DEPLOYMENT_NAME in the workflow
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # This service account is created in service.yml
      serviceAccountName: auditor-app-sa
      containers:
      - name: backend
        # IMPORTANT: This placeholder will be correctly replaced by the CI/CD pipeline
        image: DOCKER_IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
